### ISSUE TITLE
no colors

### ISSUE THREAD

**Issue by anzezupanic** [iSEE/iSEE#350] opened 2020-02-06 14:04 UTC
Hi, 

trying to visualize the example dataset in iSEE, but can-t get the visual parameters to work. Here-s the error message I get when running the shiny app. When I did the same a few months ago, everything worked fine / which makes me think that a recent package update is responsible...

```
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.
```

I guess one notification for each open plot?

**Comment by LTLA** [comment] 2020-02-07 06:55
Those notifications are irrelevant. I don't know what you mean by

> can-t get the visual parameters to work

so you'll have to be more specific.

**Comment by anzezupanic** [comment] 2020-02-07 07:48
![Picture1](https://user-images.githubusercontent.com/13380333/74010683-56448d80-4986-11ea-855f-fd1bc8bb40cf.png)
I can open the shiny app and I can choose among the data parameters, but when I click on the Visual Paramaters, I can only select among color, shape etc, but I can't assign any variables (colData) to the color, shape etc. I attached a reduced dimension figure, which i hope shows my issue.

**Comment by LTLA** [comment] 2020-02-07 08:26
Interesting.

- What is your `sessionInfo()` and browser?
- Does this still occur with the latest version (on GitHub, 1.99.0)?

The offending code occurs in the Javascript for the `conditionalPanel` responding to the check box group, which is usually guesswork for me, but I don't see too much wrong there:

https://github.com/iSEE/iSEE/blob/7e8c014c1b249289970b81f691e16ba92f34277e/R/interface_hidden.R#L96-L98

**Comment by anzezupanic** [comment] 2020-02-07 08:36
I've tried now on different browsers  after updating all, and this has solved the problem (but i need to open the app in the browser) in chrome and firefox, so thanks for the tip. 


here's the session info, if it is of any help: 

R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Slovenian_Slovenia.1250  LC_CTYPE=Slovenian_Slovenia.1250    LC_MONETARY=Slovenian_Slovenia.1250 LC_NUMERIC=C                        LC_TIME=Slovenian_Slovenia.1250    

attached base packages:
 [1] grid      parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] yaml_2.2.1                  shiny_1.4.0                 scRNAseq_1.8.0              scater_1.10.1               ggplot2_3.2.1               Gviz_1.26.5                 iSEE_1.2.4                 
 [8] SingleCellExperiment_1.4.1  SummarizedExperiment_1.12.0 DelayedArray_0.8.0          BiocParallel_1.16.6         matrixStats_0.55.0          Biobase_2.42.0              GenomicRanges_1.34.0       
[15] GenomeInfoDb_1.18.2         shinyAce_0.4.1              Rtsne_0.15                  IRanges_2.16.0              S4Vectors_0.20.1            BiocGenerics_0.28.0        

loaded via a namespace (and not attached):
  [1] backports_1.1.5           Hmisc_4.3-0               plyr_1.8.5                igraph_1.2.4.2            lazyeval_0.2.2            shinydashboard_0.7.1      splines_3.5.2             crosstalk_1.0.0          
  [9] digest_0.6.23             ensembldb_2.6.8           htmltools_0.4.0           viridis_0.5.1             rsconnect_0.8.16          magrittr_1.5              checkmate_1.9.4           memoise_1.1.0            
 [17] BSgenome_1.50.0           cluster_2.1.0             Biostrings_2.50.2         prettyunits_1.1.1         colorspace_1.4-1          blob_1.2.1                xfun_0.12                 dplyr_0.8.4              
 [25] crayon_1.3.4              RCurl_1.98-1.1            jsonlite_1.6.1            survival_2.43-3           VariantAnnotation_1.28.13 glue_1.3.1                gtable_0.3.0              zlibbioc_1.28.0          
 [33] XVector_0.22.0            Rhdf5lib_1.4.3            rentrez_1.2.2             HDF5Array_1.10.1          scales_1.1.0              DBI_1.1.0                 miniUI_0.1.1.1            Rcpp_1.0.3               
 [41] viridisLite_0.3.0         xtable_1.8-4              progress_1.2.2            htmlTable_1.13.3          foreign_0.8-71            bit_1.1-15.1              Formula_1.2-3             DT_0.12                  
 [49] htmlwidgets_1.5.1         httr_1.4.1                RColorBrewer_1.1-2        acepack_1.4.1             pkgconfig_2.0.3           XML_3.99-0.3              farver_2.0.3              nnet_7.3-12              
 [57] tidyselect_1.0.0          labeling_0.3              rlang_0.4.4               reshape2_1.4.3            later_1.0.0               AnnotationDbi_1.44.0      munsell_0.5.0             tools_3.5.2              
 [65] RSQLite_2.2.0             rintrojs_0.2.2            stringr_1.4.0             fastmap_1.0.1             knitr_1.27                bit64_0.9-7               purrr_0.3.3               AnnotationFilter_1.6.0   
 [73] nlme_3.1-137              mime_0.8                  biomaRt_2.38.0            compiler_3.5.2            rstudioapi_0.10           beeswarm_0.2.3            curl_4.3                  tibble_2.1.3             
 [81] stringi_1.4.5             GenomicFeatures_1.34.8    lattice_0.20-38           ProtGenerics_1.14.0       Matrix_1.2-15             shinyjs_1.1               vctrs_0.2.2               pillar_1.4.3             
 [89] lifecycle_0.1.0           BiocManager_1.30.10       data.table_1.12.8         cowplot_1.0.0             bitops_1.0-6              httpuv_1.5.2              rtracklayer_1.42.2        R6_2.4.1                 
 [97] latticeExtra_0.6-28       promises_1.1.0            gridExtra_2.3             vipor_0.4.5               dichromat_2.0-0           colourpicker_1.0          assertthat_0.2.1          rhdf5_2.26.2             
[105] withr_2.1.2               GenomicAlignments_1.18.1  Rsamtools_1.34.1          GenomeInfoDbData_1.2.0    mgcv_1.8-26               hms_0.5.3                 rpart_4.1-13              tidyr_1.0.2              
[113] DelayedMatrixStats_1.4.0  biovizBase_1.30.1         base64enc_0.1-3           ggbeeswarm_0.6.0

**Comment by kevinrue** [comment] 2020-02-07 10:51
You're not saying which web browser _didn't_ work, which would be a useful piece of information for other users.

**Comment by anzezupanic** [comment] 2020-02-07 11:07
it did not work on internet explorer v11.59 and on mozilla firefox v69.

**Comment by LTLA** [comment] 2020-02-07 16:28
Judging by the table at https://caniuse.com/#feat=array-includes, it seems that IE has never supported the `includes` feature. Firefox should have it, though, so that's a bit odd. Can anyone reproduce this on a local Firefox?

**Comment by kevinrue** [comment] 2020-02-11 19:37
I've just tried with Firefox 72.0.2 (64-bit) and I can't reproduce the issue.
In my hands iSEE 1.4.0 works with `R version 3.6.2 (2019-12-12)` and `BiocManager::valid()`

**Comment by kevinrue** [comment] 2020-06-07 14:37
I'm gonna close this one based on https://github.com/iSEE/iSEE/issues/350#issuecomment-583288211
> this has solved the problem

**Closed by kevinrue** 2020-06-07 14:37 UTC
